[project]
name = "TIPCommon"
version = "2.3.1"
description = "General Purpose CLI tool for Google SecOps Marketplace"
readme = "README.md"
authors = [
    { name = "Tal Shapir", email = "talshapir@google.com" },
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "google-api-python-client==2.188.0",
    "google-auth==2.47.0",
    "google-auth-httplib2==0.3.0",
    "httpx==0.28.1",
    "pycryptodome==3.23.0",
    "pyopenssl==25.3.0",
    "requests==2.32.5",
    "requests-toolbelt==1.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
    "ty>=0.0.13",
]

[build-system]
requires = ["setuptools==65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["TIPCommon*"]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
