[project]
name = "mp-describe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.8.0",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.1",
    "vera>=1.0.0",
]

[project.entry-points.vera]
mp_describe = "mp_describe.plugin_impl"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
vera = { git = "https://github.com/google/vera.git", subdirectory = "vera" }

[dependency-groups]
dev = [
    "ruff>=0.14.14",
    "ty>=0.0.14",
]

