[project]
name = "EnvironmentCommon"
version = "1.0.3"
description = "Package that deals with environment mapping in Google SecOps SOAR Connectors"
authors = [
    { name = "Tal Shapir", email = "talshapir@google.com" },
]
requires-python = "==3.11.*"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.13",
    "ty>=0.0.13",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"


[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
