[project]
name = "ServiceNow"
version = "59.0"
description = "An incident ticketing integration exchanges ticket data between your ServiceNow instance and Google SecOps system."
requires-python = ">=3.11"
dependencies = [
    "arrow>=1.4.0",
    "environmentcommon",
    "requests==2.32.3",
    "tipcommon",
]

[dependency-groups]
dev = [
    "integration-testing",
    "pytest>=9.0.2",
    "pytest-json-report>=1.5.0",
    "soar-sdk",
]

[tool.uv.sources]
tipcommon = { path = "../../../../packages/tipcommon/whls/TIPCommon-2.2.22-py2.py3-none-any.whl" }
environmentcommon = { path = "../../../../packages/envcommon/whls/EnvironmentCommon-1.0.2-py2.py3-none-any.whl" }
soar-sdk = { git = "https://github.com/chronicle/soar-sdk.git" }
integration-testing = { path = "../../../../packages/integration_testing_whls/integration_testing-2.2.22-py3-none-any.whl" }

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

