name: Get Installed Applications
description: Get a list of all installed application on a device
integration_identifier: Portnox
parameters: []
dynamic_results_metadata: []
creator: admin
simulation_data_json: '{"Entities": ["MacAddress", "ADDRESS"]}'
script_result_name: success
