[environment]
python-platform = "all"
python-version = "3.11"

[src]
exclude = ["tests/test_mp/mock_content_hub/**"]

[[overrides]]
include = [
    "tests/test_mp/test_core/test_data_models/**",
]

[overrides.rules]
missing-typed-dict-key = "ignore"
invalid-argument-type = "ignore"

[[overrides]]
include = [
    "tests/test_mp/test_validate/test_pre_build_validations/test_common/test_version_bump_validation.py",
]

[overrides.rules]
possibly-missing-attribute = "ignore"
non-subscriptable = "ignore"
invalid-argument-type = "ignore"
