[project]
name = "ReversinglabsA1000"
version = "7.1"
description = "The A1000 Malware Analysis Platform supports advanced hunting and investigations through high-speed automated static analysis."
requires-python = ">=3.11"
dependencies = [ "requests>=2.32.5",]

[dependency-groups]
dev = [ "environmentcommon",
    "integration-testing",
    "pytest>=9.0.2",
    "pytest-json-report>=1.5.0",
    "soar-sdk",
    "tipcommon",]

[tool.uv]
[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.uv.sources.soar-sdk]
git = "https://github.com/chronicle/soar-sdk.git"

[tool.uv.sources.environmentcommon]
path = "../../../../packages/envcommon/whls/EnvironmentCommon-1.0.3-py3-none-any.whl"

[tool.uv.sources.integration-testing]
path = "../../../../packages/integration_testing_whls/integration_testing-2.0.0-py3-none-any.whl"

[tool.uv.sources.tipcommon]
path = "../../../../packages/tipcommon/whls/TIPCommon-2.0.0-py2.py3-none-any.whl"
