name: Build Content-Hub

on:
  push:
    branches:
    - '**'
    paths:
    - 'content/**'
    - 'packages/**'
    - '.github/workflows/**'
  pull_request:
    branches:
    - '**'
    paths:
    - 'content/**'
    - 'packages/**'
    - '.github/workflows/**'

permissions:
  contents: read

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      mp: ${{ steps.filter.outputs.mp }}
      integration_packages: ${{ steps.filter.outputs.integration_packages }}
      response_integrations_google: ${{ steps.filter.outputs.response_integrations_google }}
      response_integrations_third_party: ${{ steps.filter.outputs.response_integrations_third_party }}
      playbooks: ${{ steps.filter.outputs.playbooks }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          mp:
            - 'packages/mp/**'
            - '.github/workflows/**'
          integration_packages:
            - 'packages/envcommon/**'
            - 'packages/tipcommon/**'
            - 'packages/integration_testing/**'
            - '/packages/integration_testing_whls'
          response_integrations_google:
            - 'content/response_integrations/google/**'
          response_integrations_third_party:
            - 'content/response_integrations/third_party/**'
          playbooks:
            - 'content/playbooks/**'

  build_google:
    name: Build Google Integrations
    needs: changes
    if: ${{ needs.changes.outputs.response_integrations_google == 'true' || needs.changes.outputs.mp == 'true' || needs.changes.outputs.integration_packages == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install uv
        uv pip install --system -e ./packages/mp

    - name: Build Google Integrations
      shell: bash
      run: |
        mp config --root-path . --processes 10 --display-config
        mp build repository google

  build_third_party:
    name: Build Third-Party Integrations
    needs: changes
    if: ${{ needs.changes.outputs.response_integrations_third_party == 'true' || needs.changes.outputs.mp == 'true' || needs.changes.outputs.integration_packages == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install uv
        uv pip install --system -e ./packages/mp

    - name: Build Third-Party Integrations
      shell: bash
      run: |
        mp config --root-path . --processes 10 --display-config
        mp build repository third_party

  build_playbooks:
    name: Build Playbooks
    needs: changes
    if: ${{ needs.changes.outputs.playbooks == 'true' || needs.changes.outputs.mp == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install uv
        uv pip install --system -e ./packages/mp

    - name: Build Playbooks
      shell: bash
      run: |
        mp config --root-path . --processes 10 --display-config
        mp build repository playbooks
