name: Python Code Checks with Static Type Checking for mp
permissions:
  contents: read
on:
  push:
    branches:
      - '**'
    paths:
      - 'packages/mp/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/mp/**'
jobs:
  mp_check:
    name: Code Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mp package and run mp check
        run: |
          pip install --upgrade pip
          pip install uv
          cd ./packages/mp
          uv sync
          source .venv/bin/activate
          uv pip install -e .

          mp config --root-path . --processes 10 --display-config
          mp check --changed-files --raise-error-on-violations --output-format grouped --static-type-check
