name: "[mp] Python Code Checks"
permissions:
  contents: read
on:
  push:
    branches:
      - '**'
    paths:
      - 'packages/mp/**'

  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/mp/**'
jobs:
  mp_check:
    name: Code Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv package
        # language=bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Run ruff
        working-directory: packages/mp
        # language=bash
        run: |
          uv sync --dev
          source .venv/bin/activate
          ruff check --output-format grouped

      - name: Run ty
        working-directory: packages/mp
        # language=bash
        run: |
          uv sync --dev
          source .venv/bin/activate
          ty check --output-format concise