name: 'Push Custom Integrations on Push'

on:
  push:
    branches:
    - main

jobs:
  push_integrations:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Push Custom Integrations'
      uses: chronicle/content-hub/actions/custom-integration-push@main
      with:
        soar_api_url: ${{ secrets.SOAR_API_URL }}
        soar_api_key: ${{ secrets.SOAR_API_KEY }}
