name: Test mp Package
permissions:
  contents: read
on:
  push:
    branches:
    - '**'
    paths:
    - 'packages/mp/**'
  pull_request:
    branches:
    - '**'
    paths:
    - 'packages/mp/**'

jobs:
  test_mp:
    name: Test mp
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv package
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv

    - name: Run pytest
      working-directory: packages/mp
      run: |
        uv sync --dev
        source .venv/bin/activate
        pytest tests -n 20 --cov