name: Windows Workflows
permissions:
  contents: read
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  test-mp-windows:
    name: 1. Test mp Package
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp
        python -m pip install pytest pytest-cov pytest-xdist hypothesis
    - name: Run pytest
      working-directory: packages/mp
      run: python -m pytest tests -n 5 --cov


  validate-integrations-windows:
    name: 2a. Validate Integrations
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mp
      run: python -m pip install -e ./packages/mp
    - name: Run Validations
      shell: pwsh
      run: |
        wmp config --root-path . --processes 5 --display-config
        wmp validate repository google third_party --only-pre-build

  run-integrations-tests-windows:
    name: 2b. Test Integrations
    needs: validate-integrations-windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mp
      run: python -m pip install -e ./packages/mp
    - name: Run integration tests
      shell: pwsh
      run: |
        wmp config --root-path . --processes 5 --display-config
        wmp test --repository third_party --repository google --raise-error-on-violations

  mp-build-integrations-windows:
    name: 2c. Build Integrations
    needs: run-integrations-tests-windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mp
      run: python -m pip install -e ./packages/mp
    - name: Build
      shell: pwsh
      run: |
        wmp config --root-path . --processes 2 --display-config
        wmp build repository google third_party 



  validate-playbooks-windows:
    name: 3a. Validate Playbooks
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mp
      run: python -m pip install -e ./packages/mp
    - name: Run Validations
      shell: pwsh
      run: |
        wmp config --root-path . --processes 5 --display-config
        wmp validate repository playbooks --only-pre-build

  mp-build-playbooks-windows:
    name: 3b. Build Playbooks
    needs: validate-playbooks-windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mp
      run: python -m pip install -e ./packages/mp
    - name: Build
      shell: pwsh
      run: |
        wmp config --root-path . --processes 5 --display-config
        wmp build repository playbooks