name: Windows Workflows
permissions:
  contents: read
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp-build-integrations-windows:
    name: Build Integrations on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Build all integrations
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp build --repository third_party --repository google

  test-mp-windows:
    name: Test mp Package on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package and required test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp
        python -m pip install pytest pytest-cov pytest-xdist hypothesis

    - name: Run pytest
      working-directory: packages/mp
      run: |
        python -m pytest tests -n 10 --cov

  validate-integrations-windows:
    name: Run Integrations Validations on windows
    runs-on: windows-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run Validations
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        PYTHONIOENCODING: "utf-8"
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp validate --repository third_party --only-pre-build

  run-integrations-tests-windows:
    name: Run Inegrations Tests on windows
    runs-on: windows-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run integration tests
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp test --repository third_party --repository google --raise-error-on-violations

  mp-build-playbooks-windows:
    name: Build Playbooks on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Build all integrations
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp build --repository playbooks

  validate-playbooks-windows:
    name: Run Playbooks Validations on windows
    runs-on: windows-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run Validations
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        PYTHONIOENCODING: "utf-8"
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp validate --repository playbooks --only-pre-build